name: Buildr
main: me.simplex.buildr.Buildr
version: 0.1
website: http://www.over9000.eu
author: simplex
description: >
             Plugin that makes building alot easier, faster and more comfortable.
commands:
  globalbuild:
    description: Toggles the Global Buildmode
    aliases: [gb,gbm]
    usage: |
           /<command>
           Example: /<command>
  build:
    description: Toggles the User Buildmode
    aliases: [ub,gbm,userbuild]
    usage: |
           /<command>
           Example: /<command>
  wall:
    description: Starts the wall building function
    usage: |
           /<command> 
           Example: /<command> place corner 1 & corner 2
  airfloor:
    description: places a block (area) of material x y blocks above the player
    usage: |
           /<command> <material #> <height #>
           Example: /<command> 4 20 3
  wool:
    description: gives a Stack of wool in the specified color to the player
    usage: |
           /<command> <color>
           Example: /<command> black
  top:
    description: ports the player to the highest block at its current position
    usage: |
           /<command> 
           Example: /<command> 
  undo:
    description: Undoes the lastest action the player used (airfloor, wall)
    aliases: [bu,buildrundo]
    usage: |
           /<command> 
           Example: /<command> 