name: Buildr
main: me.simplex.buildr.Buildr
version: 0.4.4
website: http://www.over9000.eu
author: simplex
description: >
             Collection of tools for faster & more comfortable building
commands:
  globalbuild:
    description: Toggles the Global Buildmode for the world you're in
    aliases: [gb,gbm]
    usage: |
           /<command>
           Example: /<command>
  build:
    description: Toggles the User Buildmode
    aliases: [ub,bm]
    usage: |
           /<command>
           Example: /<command>
  allowbuild:
    description: Unlocks/Locks the activation of the buildmode in the world you're in. Kicks all users out of buildmode on lock. Only has a Effect if BUILDMODE_BUILDMODE_REQUIRE_ALLOW is true
    aliases: [ab,abm,allowbm]
    usage: |
           /<command>
           Example: /<command>
  wall:
    description: Starts the wall building function
    aliases: [wl]
    usage: |
           /<command> <material #> {a|air|aironly}
  wallx:
    description: Starts the wallx building function
    aliases: [wlx]
    usage: |
           /<command> <material #> {a|air|aironly}
  cuboid:
    description: Starts the cuboid building function
    aliases: [cube,cu]
    usage: |
           /<command> <material #> {a|air|aironly} {h|hollow}
  sphere:
    description: Starts the sphere building function
    aliases: [ball,sp]
    usage: |
           /<command> <material #> {a|air|aironly} {h|hollow}
  halfsphere:
    description: Starts the half sphere building function
    aliases: [hball,hsp]
    usage: |
           /<command> <material #> {a|air|aironly} {h|hollow}
  cylinder:
    description: Starts the cylinder building function
    aliases: [cyl,tube]
    usage: |
           /<command> <material #> {a|air|aironly} {h|hollow}
  airfloor:
    description: places a block (area) of material x y blocks above the player
    aliases: [af,airf]
    usage: |
           /<command> <material #> <height #>
           Example: /<command> 4 20 3
  wool:
    description: gives a Stack of wool in the specified color to the player
    usage: |
           /<command> <color>
           Example: /<command> black
  top:
    description: ports the player to the highest block at its current position
    usage: |
           /<command> 
           Example: /<command> 
  undo:
    description: Undoes the lastest action the player used (airfloor, wall)
    aliases: [bu,buildrundo]
    usage: |
           /<command> 
           Example: /<command> 
  give:
    description: gives a Stack of items to the player
    aliases: [gv,g]
    usage: |
           /<command> <player> <itemid #|itemname> <amount #>
           Example: /<command> 20 50 gives a stack of 50 Glass to the player
  clearinv:
    description: clears the inventory of the player
    aliases: [clrinv,ci,cleari,clear,clearinventory]
    usage: |
           /<command> 
           Example: /<command>
  location:
    description: returns the location of the block under the player
    aliases: [loc,gps]
    usage: |
           /<command> 
           Example: /<command>
  jump:
    description: ports the player to the block that he is looking at
    aliases: [jmp,go]
    usage: |
           /<command> 
           Example: /<command>